apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backendAppName }}
  labels:
    app: {{ .Values.backendAppName }}
spec:
  ports:
    - port: {{ .Values.containerPort.backendPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.backendAppName }}