#Build pipeline for E2E Monitoring

trigger: none

variables:
- group: 'CSGQA-Code-Scan'

parameters:
- name: "pool"
  default: "CSG Linux"

schedules:
    - cron: '00 00 1,15 * *'
      displayName: 'Scan Job Scheduler'
      branches:
          include: ["develop"]
          exclude: []
      always: true

stages:
  
  - stage: ScanFrontEndApp
    displayName: 'Scan Front End Application'
    pool: ${{ parameters.pool }}
    dependsOn: []
    jobs:
    - template: K8S Templates/ci/app/stages/jobs/e2e.monitoring.frontend.scan.job.yml

  - stage: ScanBackEndApp
    displayName: 'Scan Back End Application'
    pool: ${{ parameters.pool }}
    dependsOn: []
    jobs:
    - template: K8S Templates/ci/app/stages/jobs/e2e.monitoring.backend.scan.job.yml

          
          
          
    
