apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.frontendAppName }}
spec:
  maxReplicas: {{ .Values.replicas.max }}
  minReplicas: {{ .Values.replicas.min }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.frontendAppName }}
  targetCPUUtilizationPercentage: 70
